### ISSUE TITLE
Bot's are having a Badly Compressed Packet issue

### ISSUE THREAD

**Issue by JAhimaz** [RavMda/go-bots#1]
Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 20 is below server threshold of 512.

Could be the proxies as well, but I'd just like to know what it may be.

**Comment by RavMda** [comment]
@JAhimaz It's not proxies problem, it's just something weird going on with packet decompression.
The problem lies here: https://github.com/RavMda/go-mc/blob/master/net/packet/packet.go#L79

**Comment by RavMda** [comment]
@JAhimaz should be fixed now
https://github.com/Tnze/go-mc/issues/95#issuecomment-798834261
